// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/product.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CategoryId    string                 `protobuf:"bytes,7,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	BrandId       string                 `protobuf:"bytes,8,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	SellerId      string                 `protobuf:"bytes,9,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	Images        []*ProductImage        `protobuf:"bytes,10,rep,name=images,proto3" json:"images,omitempty"`
	Variants      []*ProductVariant      `protobuf:"bytes,11,rep,name=variants,proto3" json:"variants,omitempty"`
	Attributes    []*ProductAttribute    `protobuf:"bytes,12,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductData) Reset() {
	*x = ProductData{}
	mi := &file_proto_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductData) ProtoMessage() {}

func (x *ProductData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductData.ProtoReflect.Descriptor instead.
func (*ProductData) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductData) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ProductData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductData) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductData) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductData) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ProductData) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ProductData) GetBrandId() string {
	if x != nil {
		return x.BrandId
	}
	return ""
}

func (x *ProductData) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *ProductData) GetImages() []*ProductImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ProductData) GetVariants() []*ProductVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *ProductData) GetAttributes() []*ProductAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type ProductImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	IsVideo       bool                   `protobuf:"varint,2,opt,name=is_video,json=isVideo,proto3" json:"is_video,omitempty"`
	SortOrder     int32                  `protobuf:"varint,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductImage) Reset() {
	*x = ProductImage{}
	mi := &file_proto_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductImage) ProtoMessage() {}

func (x *ProductImage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductImage.ProtoReflect.Descriptor instead.
func (*ProductImage) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProductImage) GetIsVideo() bool {
	if x != nil {
		return x.IsVideo
	}
	return false
}

func (x *ProductImage) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type ProductVariant struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ExternalVariantId string                 `protobuf:"bytes,1,opt,name=external_variant_id,json=externalVariantId,proto3" json:"external_variant_id,omitempty"`
	Color             string                 `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Size              string                 `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	Price             float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	OriginalPrice     float64                `protobuf:"fixed64,5,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`
	Stock             int32                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProductVariant) Reset() {
	*x = ProductVariant{}
	mi := &file_proto_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductVariant) ProtoMessage() {}

func (x *ProductVariant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductVariant.ProtoReflect.Descriptor instead.
func (*ProductVariant) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{2}
}

func (x *ProductVariant) GetExternalVariantId() string {
	if x != nil {
		return x.ExternalVariantId
	}
	return ""
}

func (x *ProductVariant) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ProductVariant) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *ProductVariant) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductVariant) GetOriginalPrice() float64 {
	if x != nil {
		return x.OriginalPrice
	}
	return 0
}

func (x *ProductVariant) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type ProductAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductAttribute) Reset() {
	*x = ProductAttribute{}
	mi := &file_proto_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAttribute) ProtoMessage() {}

func (x *ProductAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAttribute.ProtoReflect.Descriptor instead.
func (*ProductAttribute) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{3}
}

func (x *ProductAttribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductAttribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisResponse) Reset() {
	*x = AnalysisResponse{}
	mi := &file_proto_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResponse) ProtoMessage() {}

func (x *AnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResponse.ProtoReflect.Descriptor instead.
func (*AnalysisResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{4}
}

func (x *AnalysisResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AnalysisResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_product_proto protoreflect.FileDescriptor

const file_proto_product_proto_rawDesc = "" +
	"\n" +
	"\x13proto/product.proto\x12\aproduct\"\xa5\x03\n" +
	"\vProductData\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12\x1f\n" +
	"\vcategory_id\x18\a \x01(\tR\n" +
	"categoryId\x12\x19\n" +
	"\bbrand_id\x18\b \x01(\tR\abrandId\x12\x1b\n" +
	"\tseller_id\x18\t \x01(\tR\bsellerId\x12-\n" +
	"\x06images\x18\n" +
	" \x03(\v2\x15.product.ProductImageR\x06images\x123\n" +
	"\bvariants\x18\v \x03(\v2\x17.product.ProductVariantR\bvariants\x129\n" +
	"\n" +
	"attributes\x18\f \x03(\v2\x19.product.ProductAttributeR\n" +
	"attributes\"Z\n" +
	"\fProductImage\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x19\n" +
	"\bis_video\x18\x02 \x01(\bR\aisVideo\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\x05R\tsortOrder\"\xbd\x01\n" +
	"\x0eProductVariant\x12.\n" +
	"\x13external_variant_id\x18\x01 \x01(\tR\x11externalVariantId\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\x12\x12\n" +
	"\x04size\x18\x03 \x01(\tR\x04size\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12%\n" +
	"\x0eoriginal_price\x18\x05 \x01(\x01R\roriginalPrice\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x05R\x05stock\"<\n" +
	"\x10ProductAttribute\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"D\n" +
	"\x10AnalysisResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2]\n" +
	"\x16ProductAnalysisService\x12C\n" +
	"\x0eAnalyzeProduct\x12\x14.product.ProductData\x1a\x19.product.AnalysisResponse\"\x00B\x0fZ\rcrawler/protob\x06proto3"

var (
	file_proto_product_proto_rawDescOnce sync.Once
	file_proto_product_proto_rawDescData []byte
)

func file_proto_product_proto_rawDescGZIP() []byte {
	file_proto_product_proto_rawDescOnce.Do(func() {
		file_proto_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_proto_rawDesc), len(file_proto_product_proto_rawDesc)))
	})
	return file_proto_product_proto_rawDescData
}

var file_proto_product_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_product_proto_goTypes = []any{
	(*ProductData)(nil),      // 0: product.ProductData
	(*ProductImage)(nil),     // 1: product.ProductImage
	(*ProductVariant)(nil),   // 2: product.ProductVariant
	(*ProductAttribute)(nil), // 3: product.ProductAttribute
	(*AnalysisResponse)(nil), // 4: product.AnalysisResponse
}
var file_proto_product_proto_depIdxs = []int32{
	1, // 0: product.ProductData.images:type_name -> product.ProductImage
	2, // 1: product.ProductData.variants:type_name -> product.ProductVariant
	3, // 2: product.ProductData.attributes:type_name -> product.ProductAttribute
	0, // 3: product.ProductAnalysisService.AnalyzeProduct:input_type -> product.ProductData
	4, // 4: product.ProductAnalysisService.AnalyzeProduct:output_type -> product.AnalysisResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_product_proto_init() }
func file_proto_product_proto_init() {
	if File_proto_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_proto_rawDesc), len(file_proto_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_proto_goTypes,
		DependencyIndexes: file_proto_product_proto_depIdxs,
		MessageInfos:      file_proto_product_proto_msgTypes,
	}.Build()
	File_proto_product_proto = out.File
	file_proto_product_proto_goTypes = nil
	file_proto_product_proto_depIdxs = nil
}
