// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/product.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductAnalysisService_AnalyzeProduct_FullMethodName = "/product.ProductAnalysisService/AnalyzeProduct"
)

// ProductAnalysisServiceClient is the client API for ProductAnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductAnalysisServiceClient interface {
	AnalyzeProduct(ctx context.Context, in *ProductData, opts ...grpc.CallOption) (*AnalysisResponse, error)
}

type productAnalysisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductAnalysisServiceClient(cc grpc.ClientConnInterface) ProductAnalysisServiceClient {
	return &productAnalysisServiceClient{cc}
}

func (c *productAnalysisServiceClient) AnalyzeProduct(ctx context.Context, in *ProductData, opts ...grpc.CallOption) (*AnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalysisResponse)
	err := c.cc.Invoke(ctx, ProductAnalysisService_AnalyzeProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductAnalysisServiceServer is the server API for ProductAnalysisService service.
// All implementations must embed UnimplementedProductAnalysisServiceServer
// for forward compatibility.
type ProductAnalysisServiceServer interface {
	AnalyzeProduct(context.Context, *ProductData) (*AnalysisResponse, error)
	mustEmbedUnimplementedProductAnalysisServiceServer()
}

// UnimplementedProductAnalysisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductAnalysisServiceServer struct{}

func (UnimplementedProductAnalysisServiceServer) AnalyzeProduct(context.Context, *ProductData) (*AnalysisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeProduct not implemented")
}
func (UnimplementedProductAnalysisServiceServer) mustEmbedUnimplementedProductAnalysisServiceServer() {
}
func (UnimplementedProductAnalysisServiceServer) testEmbeddedByValue() {}

// UnsafeProductAnalysisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductAnalysisServiceServer will
// result in compilation errors.
type UnsafeProductAnalysisServiceServer interface {
	mustEmbedUnimplementedProductAnalysisServiceServer()
}

func RegisterProductAnalysisServiceServer(s grpc.ServiceRegistrar, srv ProductAnalysisServiceServer) {
	// If the following call pancis, it indicates UnimplementedProductAnalysisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductAnalysisService_ServiceDesc, srv)
}

func _ProductAnalysisService_AnalyzeProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAnalysisServiceServer).AnalyzeProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductAnalysisService_AnalyzeProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAnalysisServiceServer).AnalyzeProduct(ctx, req.(*ProductData))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductAnalysisService_ServiceDesc is the grpc.ServiceDesc for ProductAnalysisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductAnalysisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductAnalysisService",
	HandlerType: (*ProductAnalysisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeProduct",
			Handler:    _ProductAnalysisService_AnalyzeProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/product.proto",
}
