// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/product_analysis.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductAnalysisService_Health_FullMethodName                = "/product_analysis.ProductAnalysisService/Health"
	ProductAnalysisService_AnalyzeProduct_FullMethodName        = "/product_analysis.ProductAnalysisService/AnalyzeProduct"
	ProductAnalysisService_UpdateProductPriority_FullMethodName = "/product_analysis.ProductAnalysisService/UpdateProductPriority"
	ProductAnalysisService_GetProductAnalytics_FullMethodName   = "/product_analysis.ProductAnalysisService/GetProductAnalytics"
)

// ProductAnalysisServiceClient is the client API for ProductAnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductAnalysisServiceClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	AnalyzeProduct(ctx context.Context, in *AnalyzeProductRequest, opts ...grpc.CallOption) (*AnalyzeProductResponse, error)
	UpdateProductPriority(ctx context.Context, in *UpdateProductPriorityRequest, opts ...grpc.CallOption) (*UpdateProductPriorityResponse, error)
	GetProductAnalytics(ctx context.Context, in *GetProductAnalyticsRequest, opts ...grpc.CallOption) (*GetProductAnalyticsResponse, error)
}

type productAnalysisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductAnalysisServiceClient(cc grpc.ClientConnInterface) ProductAnalysisServiceClient {
	return &productAnalysisServiceClient{cc}
}

func (c *productAnalysisServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ProductAnalysisService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productAnalysisServiceClient) AnalyzeProduct(ctx context.Context, in *AnalyzeProductRequest, opts ...grpc.CallOption) (*AnalyzeProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeProductResponse)
	err := c.cc.Invoke(ctx, ProductAnalysisService_AnalyzeProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productAnalysisServiceClient) UpdateProductPriority(ctx context.Context, in *UpdateProductPriorityRequest, opts ...grpc.CallOption) (*UpdateProductPriorityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProductPriorityResponse)
	err := c.cc.Invoke(ctx, ProductAnalysisService_UpdateProductPriority_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productAnalysisServiceClient) GetProductAnalytics(ctx context.Context, in *GetProductAnalyticsRequest, opts ...grpc.CallOption) (*GetProductAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductAnalyticsResponse)
	err := c.cc.Invoke(ctx, ProductAnalysisService_GetProductAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductAnalysisServiceServer is the server API for ProductAnalysisService service.
// All implementations must embed UnimplementedProductAnalysisServiceServer
// for forward compatibility.
type ProductAnalysisServiceServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	AnalyzeProduct(context.Context, *AnalyzeProductRequest) (*AnalyzeProductResponse, error)
	UpdateProductPriority(context.Context, *UpdateProductPriorityRequest) (*UpdateProductPriorityResponse, error)
	GetProductAnalytics(context.Context, *GetProductAnalyticsRequest) (*GetProductAnalyticsResponse, error)
	mustEmbedUnimplementedProductAnalysisServiceServer()
}

// UnimplementedProductAnalysisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductAnalysisServiceServer struct{}

func (UnimplementedProductAnalysisServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedProductAnalysisServiceServer) AnalyzeProduct(context.Context, *AnalyzeProductRequest) (*AnalyzeProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeProduct not implemented")
}
func (UnimplementedProductAnalysisServiceServer) UpdateProductPriority(context.Context, *UpdateProductPriorityRequest) (*UpdateProductPriorityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProductPriority not implemented")
}
func (UnimplementedProductAnalysisServiceServer) GetProductAnalytics(context.Context, *GetProductAnalyticsRequest) (*GetProductAnalyticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductAnalytics not implemented")
}
func (UnimplementedProductAnalysisServiceServer) mustEmbedUnimplementedProductAnalysisServiceServer() {
}
func (UnimplementedProductAnalysisServiceServer) testEmbeddedByValue() {}

// UnsafeProductAnalysisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductAnalysisServiceServer will
// result in compilation errors.
type UnsafeProductAnalysisServiceServer interface {
	mustEmbedUnimplementedProductAnalysisServiceServer()
}

func RegisterProductAnalysisServiceServer(s grpc.ServiceRegistrar, srv ProductAnalysisServiceServer) {
	// If the following call pancis, it indicates UnimplementedProductAnalysisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductAnalysisService_ServiceDesc, srv)
}

func _ProductAnalysisService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAnalysisServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductAnalysisService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAnalysisServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductAnalysisService_AnalyzeProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAnalysisServiceServer).AnalyzeProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductAnalysisService_AnalyzeProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAnalysisServiceServer).AnalyzeProduct(ctx, req.(*AnalyzeProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductAnalysisService_UpdateProductPriority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductPriorityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAnalysisServiceServer).UpdateProductPriority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductAnalysisService_UpdateProductPriority_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAnalysisServiceServer).UpdateProductPriority(ctx, req.(*UpdateProductPriorityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductAnalysisService_GetProductAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAnalysisServiceServer).GetProductAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductAnalysisService_GetProductAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAnalysisServiceServer).GetProductAnalytics(ctx, req.(*GetProductAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductAnalysisService_ServiceDesc is the grpc.ServiceDesc for ProductAnalysisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductAnalysisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product_analysis.ProductAnalysisService",
	HandlerType: (*ProductAnalysisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _ProductAnalysisService_Health_Handler,
		},
		{
			MethodName: "AnalyzeProduct",
			Handler:    _ProductAnalysisService_AnalyzeProduct_Handler,
		},
		{
			MethodName: "UpdateProductPriority",
			Handler:    _ProductAnalysisService_UpdateProductPriority_Handler,
		},
		{
			MethodName: "GetProductAnalytics",
			Handler:    _ProductAnalysisService_GetProductAnalytics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/product_analysis.proto",
}
