// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/product_analysis.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_product_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_analysis_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_product_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ProductData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CategoryId         string                 `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	BrandId            string                 `protobuf:"bytes,5,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	SellerId           string                 `protobuf:"bytes,6,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	RatingScore        float32                `protobuf:"fixed32,7,opt,name=rating_score,json=ratingScore,proto3" json:"rating_score,omitempty"`
	FavoriteCount      int32                  `protobuf:"varint,8,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`
	CommentCount       int32                  `protobuf:"varint,9,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	ViewCount          int32                  `protobuf:"varint,10,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	AddToCartCount     int32                  `protobuf:"varint,11,opt,name=add_to_cart_count,json=addToCartCount,proto3" json:"add_to_cart_count,omitempty"`
	OrderCount         int32                  `protobuf:"varint,12,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	SizeRecommendation string                 `protobuf:"bytes,13,opt,name=size_recommendation,json=sizeRecommendation,proto3" json:"size_recommendation,omitempty"`
	EstimatedDelivery  string                 `protobuf:"bytes,14,opt,name=estimated_delivery,json=estimatedDelivery,proto3" json:"estimated_delivery,omitempty"`
	IsActive           bool                   `protobuf:"varint,15,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Variants           []*ProductVariant      `protobuf:"bytes,16,rep,name=variants,proto3" json:"variants,omitempty"`
	Images             []*ProductImage        `protobuf:"bytes,17,rep,name=images,proto3" json:"images,omitempty"`
	Attributes         []*ProductAttribute    `protobuf:"bytes,18,rep,name=attributes,proto3" json:"attributes,omitempty"`
	SimilarProductIds  []string               `protobuf:"bytes,19,rep,name=similar_product_ids,json=similarProductIds,proto3" json:"similar_product_ids,omitempty"`
	TopReviews         []*Review              `protobuf:"bytes,20,rep,name=top_reviews,json=topReviews,proto3" json:"top_reviews,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProductData) Reset() {
	*x = ProductData{}
	mi := &file_proto_product_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductData) ProtoMessage() {}

func (x *ProductData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductData.ProtoReflect.Descriptor instead.
func (*ProductData) Descriptor() ([]byte, []int) {
	return file_proto_product_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *ProductData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductData) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ProductData) GetBrandId() string {
	if x != nil {
		return x.BrandId
	}
	return ""
}

func (x *ProductData) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *ProductData) GetRatingScore() float32 {
	if x != nil {
		return x.RatingScore
	}
	return 0
}

func (x *ProductData) GetFavoriteCount() int32 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

func (x *ProductData) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *ProductData) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *ProductData) GetAddToCartCount() int32 {
	if x != nil {
		return x.AddToCartCount
	}
	return 0
}

func (x *ProductData) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *ProductData) GetSizeRecommendation() string {
	if x != nil {
		return x.SizeRecommendation
	}
	return ""
}

func (x *ProductData) GetEstimatedDelivery() string {
	if x != nil {
		return x.EstimatedDelivery
	}
	return ""
}

func (x *ProductData) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ProductData) GetVariants() []*ProductVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *ProductData) GetImages() []*ProductImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ProductData) GetAttributes() []*ProductAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ProductData) GetSimilarProductIds() []string {
	if x != nil {
		return x.SimilarProductIds
	}
	return nil
}

func (x *ProductData) GetTopReviews() []*Review {
	if x != nil {
		return x.TopReviews
	}
	return nil
}

type ProductVariant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sku           string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Size          string                 `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	Price         float32                `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	OriginalPrice float32                `protobuf:"fixed32,6,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`
	StockQuantity int32                  `protobuf:"varint,7,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductVariant) Reset() {
	*x = ProductVariant{}
	mi := &file_proto_product_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductVariant) ProtoMessage() {}

func (x *ProductVariant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductVariant.ProtoReflect.Descriptor instead.
func (*ProductVariant) Descriptor() ([]byte, []int) {
	return file_proto_product_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *ProductVariant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductVariant) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ProductVariant) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ProductVariant) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *ProductVariant) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductVariant) GetOriginalPrice() float32 {
	if x != nil {
		return x.OriginalPrice
	}
	return 0
}

func (x *ProductVariant) GetStockQuantity() int32 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

func (x *ProductVariant) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type ProductImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	SortOrder     int32                  `protobuf:"varint,2,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	IsVideo       bool                   `protobuf:"varint,3,opt,name=is_video,json=isVideo,proto3" json:"is_video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductImage) Reset() {
	*x = ProductImage{}
	mi := &file_proto_product_analysis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductImage) ProtoMessage() {}

func (x *ProductImage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_analysis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductImage.ProtoReflect.Descriptor instead.
func (*ProductImage) Descriptor() ([]byte, []int) {
	return file_proto_product_analysis_proto_rawDescGZIP(), []int{4}
}

func (x *ProductImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProductImage) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *ProductImage) GetIsVideo() bool {
	if x != nil {
		return x.IsVideo
	}
	return false
}

type ProductAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductAttribute) Reset() {
	*x = ProductAttribute{}
	mi := &file_proto_product_analysis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAttribute) ProtoMessage() {}

func (x *ProductAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_analysis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAttribute.ProtoReflect.Descriptor instead.
func (*ProductAttribute) Descriptor() ([]byte, []int) {
	return file_proto_product_analysis_proto_rawDescGZIP(), []int{5}
}

func (x *ProductAttribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductAttribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rating        int32                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	ReviewerName  string                 `protobuf:"bytes,4,opt,name=reviewer_name,json=reviewerName,proto3" json:"reviewer_name,omitempty"`
	ReviewDate    string                 `protobuf:"bytes,5,opt,name=review_date,json=reviewDate,proto3" json:"review_date,omitempty"`
	IsTopReview   bool                   `protobuf:"varint,6,opt,name=is_top_review,json=isTopReview,proto3" json:"is_top_review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_proto_product_analysis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_analysis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_proto_product_analysis_proto_rawDescGZIP(), []int{6}
}

func (x *Review) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Review) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Review) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Review) GetReviewerName() string {
	if x != nil {
		return x.ReviewerName
	}
	return ""
}

func (x *Review) GetReviewDate() string {
	if x != nil {
		return x.ReviewDate
	}
	return ""
}

func (x *Review) GetIsTopReview() bool {
	if x != nil {
		return x.IsTopReview
	}
	return false
}

type AnalyzeProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *ProductData           `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeProductRequest) Reset() {
	*x = AnalyzeProductRequest{}
	mi := &file_proto_product_analysis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeProductRequest) ProtoMessage() {}

func (x *AnalyzeProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_analysis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeProductRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_analysis_proto_rawDescGZIP(), []int{7}
}

func (x *AnalyzeProductRequest) GetProduct() *ProductData {
	if x != nil {
		return x.Product
	}
	return nil
}

type AnalyzeProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Notifications []string               `protobuf:"bytes,2,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeProductResponse) Reset() {
	*x = AnalyzeProductResponse{}
	mi := &file_proto_product_analysis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeProductResponse) ProtoMessage() {}

func (x *AnalyzeProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_analysis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeProductResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_analysis_proto_rawDescGZIP(), []int{8}
}

func (x *AnalyzeProductResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AnalyzeProductResponse) GetNotifications() []string {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type UpdateProductPriorityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	IsFavorited   bool                   `protobuf:"varint,2,opt,name=is_favorited,json=isFavorited,proto3" json:"is_favorited,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductPriorityRequest) Reset() {
	*x = UpdateProductPriorityRequest{}
	mi := &file_proto_product_analysis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductPriorityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductPriorityRequest) ProtoMessage() {}

func (x *UpdateProductPriorityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_analysis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductPriorityRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductPriorityRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_analysis_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProductPriorityRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateProductPriorityRequest) GetIsFavorited() bool {
	if x != nil {
		return x.IsFavorited
	}
	return false
}

type UpdateProductPriorityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductPriorityResponse) Reset() {
	*x = UpdateProductPriorityResponse{}
	mi := &file_proto_product_analysis_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductPriorityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductPriorityResponse) ProtoMessage() {}

func (x *UpdateProductPriorityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_analysis_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductPriorityResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductPriorityResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_analysis_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateProductPriorityResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetProductAnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductAnalyticsRequest) Reset() {
	*x = GetProductAnalyticsRequest{}
	mi := &file_proto_product_analysis_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductAnalyticsRequest) ProtoMessage() {}

func (x *GetProductAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_analysis_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*GetProductAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_analysis_proto_rawDescGZIP(), []int{11}
}

func (x *GetProductAnalyticsRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type GetProductAnalyticsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PriceTrend         float32                `protobuf:"fixed32,1,opt,name=price_trend,json=priceTrend,proto3" json:"price_trend,omitempty"`
	StockTrend         float32                `protobuf:"fixed32,2,opt,name=stock_trend,json=stockTrend,proto3" json:"stock_trend,omitempty"`
	FavoriteCountTrend int32                  `protobuf:"varint,3,opt,name=favorite_count_trend,json=favoriteCountTrend,proto3" json:"favorite_count_trend,omitempty"`
	PopularityScore    float32                `protobuf:"fixed32,4,opt,name=popularity_score,json=popularityScore,proto3" json:"popularity_score,omitempty"`
	PriceHistory       []*PriceHistory        `protobuf:"bytes,5,rep,name=price_history,json=priceHistory,proto3" json:"price_history,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetProductAnalyticsResponse) Reset() {
	*x = GetProductAnalyticsResponse{}
	mi := &file_proto_product_analysis_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductAnalyticsResponse) ProtoMessage() {}

func (x *GetProductAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_analysis_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*GetProductAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_analysis_proto_rawDescGZIP(), []int{12}
}

func (x *GetProductAnalyticsResponse) GetPriceTrend() float32 {
	if x != nil {
		return x.PriceTrend
	}
	return 0
}

func (x *GetProductAnalyticsResponse) GetStockTrend() float32 {
	if x != nil {
		return x.StockTrend
	}
	return 0
}

func (x *GetProductAnalyticsResponse) GetFavoriteCountTrend() int32 {
	if x != nil {
		return x.FavoriteCountTrend
	}
	return 0
}

func (x *GetProductAnalyticsResponse) GetPopularityScore() float32 {
	if x != nil {
		return x.PopularityScore
	}
	return 0
}

func (x *GetProductAnalyticsResponse) GetPriceHistory() []*PriceHistory {
	if x != nil {
		return x.PriceHistory
	}
	return nil
}

type PriceHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VariantId     string                 `protobuf:"bytes,1,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	OldPrice      float32                `protobuf:"fixed32,2,opt,name=old_price,json=oldPrice,proto3" json:"old_price,omitempty"`
	NewPrice      float32                `protobuf:"fixed32,3,opt,name=new_price,json=newPrice,proto3" json:"new_price,omitempty"`
	ChangedAt     string                 `protobuf:"bytes,4,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceHistory) Reset() {
	*x = PriceHistory{}
	mi := &file_proto_product_analysis_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceHistory) ProtoMessage() {}

func (x *PriceHistory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_analysis_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceHistory.ProtoReflect.Descriptor instead.
func (*PriceHistory) Descriptor() ([]byte, []int) {
	return file_proto_product_analysis_proto_rawDescGZIP(), []int{13}
}

func (x *PriceHistory) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *PriceHistory) GetOldPrice() float32 {
	if x != nil {
		return x.OldPrice
	}
	return 0
}

func (x *PriceHistory) GetNewPrice() float32 {
	if x != nil {
		return x.NewPrice
	}
	return 0
}

func (x *PriceHistory) GetChangedAt() string {
	if x != nil {
		return x.ChangedAt
	}
	return ""
}

var File_proto_product_analysis_proto protoreflect.FileDescriptor

const file_proto_product_analysis_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/product_analysis.proto\x12\x10product_analysis\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xa8\x06\n" +
	"\vProductData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\tR\n" +
	"categoryId\x12\x19\n" +
	"\bbrand_id\x18\x05 \x01(\tR\abrandId\x12\x1b\n" +
	"\tseller_id\x18\x06 \x01(\tR\bsellerId\x12!\n" +
	"\frating_score\x18\a \x01(\x02R\vratingScore\x12%\n" +
	"\x0efavorite_count\x18\b \x01(\x05R\rfavoriteCount\x12#\n" +
	"\rcomment_count\x18\t \x01(\x05R\fcommentCount\x12\x1d\n" +
	"\n" +
	"view_count\x18\n" +
	" \x01(\x05R\tviewCount\x12)\n" +
	"\x11add_to_cart_count\x18\v \x01(\x05R\x0eaddToCartCount\x12\x1f\n" +
	"\vorder_count\x18\f \x01(\x05R\n" +
	"orderCount\x12/\n" +
	"\x13size_recommendation\x18\r \x01(\tR\x12sizeRecommendation\x12-\n" +
	"\x12estimated_delivery\x18\x0e \x01(\tR\x11estimatedDelivery\x12\x1b\n" +
	"\tis_active\x18\x0f \x01(\bR\bisActive\x12<\n" +
	"\bvariants\x18\x10 \x03(\v2 .product_analysis.ProductVariantR\bvariants\x126\n" +
	"\x06images\x18\x11 \x03(\v2\x1e.product_analysis.ProductImageR\x06images\x12B\n" +
	"\n" +
	"attributes\x18\x12 \x03(\v2\".product_analysis.ProductAttributeR\n" +
	"attributes\x12.\n" +
	"\x13similar_product_ids\x18\x13 \x03(\tR\x11similarProductIds\x129\n" +
	"\vtop_reviews\x18\x14 \x03(\v2\x18.product_analysis.ReviewR\n" +
	"topReviews\"\xdd\x01\n" +
	"\x0eProductVariant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x12\n" +
	"\x04size\x18\x04 \x01(\tR\x04size\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x02R\x05price\x12%\n" +
	"\x0eoriginal_price\x18\x06 \x01(\x02R\roriginalPrice\x12%\n" +
	"\x0estock_quantity\x18\a \x01(\x05R\rstockQuantity\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\"Z\n" +
	"\fProductImage\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x02 \x01(\x05R\tsortOrder\x12\x19\n" +
	"\bis_video\x18\x03 \x01(\bR\aisVideo\"<\n" +
	"\x10ProductAttribute\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xb4\x01\n" +
	"\x06Review\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12#\n" +
	"\rreviewer_name\x18\x04 \x01(\tR\freviewerName\x12\x1f\n" +
	"\vreview_date\x18\x05 \x01(\tR\n" +
	"reviewDate\x12\"\n" +
	"\ris_top_review\x18\x06 \x01(\bR\visTopReview\"P\n" +
	"\x15AnalyzeProductRequest\x127\n" +
	"\aproduct\x18\x01 \x01(\v2\x1d.product_analysis.ProductDataR\aproduct\"V\n" +
	"\x16AnalyzeProductResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12$\n" +
	"\rnotifications\x18\x02 \x03(\tR\rnotifications\"`\n" +
	"\x1cUpdateProductPriorityRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fis_favorited\x18\x02 \x01(\bR\visFavorited\"7\n" +
	"\x1dUpdateProductPriorityResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\";\n" +
	"\x1aGetProductAnalyticsRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\x81\x02\n" +
	"\x1bGetProductAnalyticsResponse\x12\x1f\n" +
	"\vprice_trend\x18\x01 \x01(\x02R\n" +
	"priceTrend\x12\x1f\n" +
	"\vstock_trend\x18\x02 \x01(\x02R\n" +
	"stockTrend\x120\n" +
	"\x14favorite_count_trend\x18\x03 \x01(\x05R\x12favoriteCountTrend\x12)\n" +
	"\x10popularity_score\x18\x04 \x01(\x02R\x0fpopularityScore\x12C\n" +
	"\rprice_history\x18\x05 \x03(\v2\x1e.product_analysis.PriceHistoryR\fpriceHistory\"\x86\x01\n" +
	"\fPriceHistory\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x01 \x01(\tR\tvariantId\x12\x1b\n" +
	"\told_price\x18\x02 \x01(\x02R\boldPrice\x12\x1b\n" +
	"\tnew_price\x18\x03 \x01(\x02R\bnewPrice\x12\x1d\n" +
	"\n" +
	"changed_at\x18\x04 \x01(\tR\tchangedAt2\xc0\x03\n" +
	"\x16ProductAnalysisService\x12M\n" +
	"\x06Health\x12\x1f.product_analysis.HealthRequest\x1a .product_analysis.HealthResponse\"\x00\x12e\n" +
	"\x0eAnalyzeProduct\x12'.product_analysis.AnalyzeProductRequest\x1a(.product_analysis.AnalyzeProductResponse\"\x00\x12z\n" +
	"\x15UpdateProductPriority\x12..product_analysis.UpdateProductPriorityRequest\x1a/.product_analysis.UpdateProductPriorityResponse\"\x00\x12t\n" +
	"\x13GetProductAnalytics\x12,.product_analysis.GetProductAnalyticsRequest\x1a-.product_analysis.GetProductAnalyticsResponse\"\x00BBZ@github.com/faisaloncode/ecommerce-crawler/product-analysis/protob\x06proto3"

var (
	file_proto_product_analysis_proto_rawDescOnce sync.Once
	file_proto_product_analysis_proto_rawDescData []byte
)

func file_proto_product_analysis_proto_rawDescGZIP() []byte {
	file_proto_product_analysis_proto_rawDescOnce.Do(func() {
		file_proto_product_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_analysis_proto_rawDesc), len(file_proto_product_analysis_proto_rawDesc)))
	})
	return file_proto_product_analysis_proto_rawDescData
}

var file_proto_product_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_product_analysis_proto_goTypes = []any{
	(*HealthRequest)(nil),                 // 0: product_analysis.HealthRequest
	(*HealthResponse)(nil),                // 1: product_analysis.HealthResponse
	(*ProductData)(nil),                   // 2: product_analysis.ProductData
	(*ProductVariant)(nil),                // 3: product_analysis.ProductVariant
	(*ProductImage)(nil),                  // 4: product_analysis.ProductImage
	(*ProductAttribute)(nil),              // 5: product_analysis.ProductAttribute
	(*Review)(nil),                        // 6: product_analysis.Review
	(*AnalyzeProductRequest)(nil),         // 7: product_analysis.AnalyzeProductRequest
	(*AnalyzeProductResponse)(nil),        // 8: product_analysis.AnalyzeProductResponse
	(*UpdateProductPriorityRequest)(nil),  // 9: product_analysis.UpdateProductPriorityRequest
	(*UpdateProductPriorityResponse)(nil), // 10: product_analysis.UpdateProductPriorityResponse
	(*GetProductAnalyticsRequest)(nil),    // 11: product_analysis.GetProductAnalyticsRequest
	(*GetProductAnalyticsResponse)(nil),   // 12: product_analysis.GetProductAnalyticsResponse
	(*PriceHistory)(nil),                  // 13: product_analysis.PriceHistory
}
var file_proto_product_analysis_proto_depIdxs = []int32{
	3,  // 0: product_analysis.ProductData.variants:type_name -> product_analysis.ProductVariant
	4,  // 1: product_analysis.ProductData.images:type_name -> product_analysis.ProductImage
	5,  // 2: product_analysis.ProductData.attributes:type_name -> product_analysis.ProductAttribute
	6,  // 3: product_analysis.ProductData.top_reviews:type_name -> product_analysis.Review
	2,  // 4: product_analysis.AnalyzeProductRequest.product:type_name -> product_analysis.ProductData
	13, // 5: product_analysis.GetProductAnalyticsResponse.price_history:type_name -> product_analysis.PriceHistory
	0,  // 6: product_analysis.ProductAnalysisService.Health:input_type -> product_analysis.HealthRequest
	7,  // 7: product_analysis.ProductAnalysisService.AnalyzeProduct:input_type -> product_analysis.AnalyzeProductRequest
	9,  // 8: product_analysis.ProductAnalysisService.UpdateProductPriority:input_type -> product_analysis.UpdateProductPriorityRequest
	11, // 9: product_analysis.ProductAnalysisService.GetProductAnalytics:input_type -> product_analysis.GetProductAnalyticsRequest
	1,  // 10: product_analysis.ProductAnalysisService.Health:output_type -> product_analysis.HealthResponse
	8,  // 11: product_analysis.ProductAnalysisService.AnalyzeProduct:output_type -> product_analysis.AnalyzeProductResponse
	10, // 12: product_analysis.ProductAnalysisService.UpdateProductPriority:output_type -> product_analysis.UpdateProductPriorityResponse
	12, // 13: product_analysis.ProductAnalysisService.GetProductAnalytics:output_type -> product_analysis.GetProductAnalyticsResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_product_analysis_proto_init() }
func file_proto_product_analysis_proto_init() {
	if File_proto_product_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_analysis_proto_rawDesc), len(file_proto_product_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_analysis_proto_goTypes,
		DependencyIndexes: file_proto_product_analysis_proto_depIdxs,
		MessageInfos:      file_proto_product_analysis_proto_msgTypes,
	}.Build()
	File_proto_product_analysis_proto = out.File
	file_proto_product_analysis_proto_goTypes = nil
	file_proto_product_analysis_proto_depIdxs = nil
}
